### ISSUE TITLE
File Missing

### ISSUE THREAD

**Issue by randiveomkar95** [mozilla/moz-sql-parser#10]
It shows README.txt is missing

**Comment by klahnakoski** [comment]
Good point.  

The README.txt is generated by another script while packaging for PyPi.  That script converts *.md to *.rst so it shows "better" in the PyPi. The README.txt is in the pypi package, but certainly does not look better :/ 

It appears PyPi has a new interface, [and it accepts markdown](https://packaging.python.org/tutorials/distributing-packages/#readme-rst-readme-md).  The`setup.py` script can be changed, and the deploy script simplified.

**Comment by klahnakoski** [comment]
requirements.txt and setuptools.json combine to replace the setup.py.

https://github.com/mozilla/moz-sql-parser/commit/6e198d6af319628e790d2ea1b0e01c701aeecb6a
