### ISSUE TITLE
json parse inconsistence

### ISSUE THREAD

**Issue by ng2dev** [mozilla/moz-sql-parser#102]
hi - right now the json parse is inconsitent to parse for a strongly typed language.
take this example:

    SELECT emp_no, MAX(from_date) FROM dept_emp AS from_date, MAX(to_date) AS to_date GROUP BY emp_no

produces this json:

     {"select": [{"value": "emp_no"}, {"value": {"max": "from_date"}, "name": "from_date"}, {"value": {"max": "to_date"}, "name": "to_date"}], "from": "dept_emp", "groupby": {"value": "emp_no"}}

the in-consistence is in the value type which is string or object

    {"value": "emp_no"}, {"value": {"max": "from_date"}

it would be more useful to produce always a map string of string that can account for special sql keywords like the max function from the example
 
    {"value": {"column": "emp_no"}}, {"value": {"max": "from_date"}

**Comment by klahnakoski** [comment]
@ng2dev  this can not be fixed:  The function calls can be arbitrarily deep.

* `"emp_no"`
* `{"max": "emp_no"}`
* `{"floor": {"max": "emp_no}}`
* `{"int": {"floor": {"max": "emp_no}}}`

If you are using a strictly typed language, be sure to use a datatype that can handle JSON, or a union of all the JSON types: `union(object, array, string, number, ...)`
