### ISSUE TITLE
Incorrect priority of operators

### ISSUE THREAD

**Issue by Epithumia** [mozilla/moz-sql-parser#106]
The AND and OR operators are incorrectly parsed (the priority is reversed it seems).
a AND b OR c is the same as (a AND b) OR c
I know that order of precedence is tricky because each vendor has particulars, but NOT > AND > OR is pretty much universal

Example:
```sql
SELECT *
FROM MyTable
GROUP BY Col
HAVING AVG(X) >= 2
AND AVG(X) <= 4
OR AVG(X) = 5;
```
is parsed as:
```python
{'select': '*', 
'from': 'MyTable', 
'groupby': {'value': 'Col'}, 
'having': {'and': [{'gte': [{'avg': 'X'}, 2]}, {'or': [{'lte': [{'avg': 'X'}, 4]}, {'eq': [{'avg': 'X'}, 5]}]}]}}
```
It should be:
```python
{'select': '*', 
'from': 'MyTable', 
'groupby': {'value': 'Col'}, 
'having': {'or': [{'and': [{'gte': [{'avg': 'X'}, 2]}, {'lte': [{'avg': 'X'}, 4]}]}, {'eq': [{'avg': 'X'}, 5]}]}
```

Conversely, calling format() on both yields the original query, which also shows that order of precedence isn't consistent (and the formatter should really use parentheses).

**Comment by klahnakoski** [comment]
Will be fixed shortly in https://github.com/mozilla/moz-sql-parser/pull/111/commits/a2b31a27b0b41e3513200f9d39ffd4a10eb1c053
