### ISSUE TITLE
Can we generate a sql query according to a modified json data?

### ISSUE THREAD

**Issue by hby2013** [mozilla/moz-sql-parser#108]
This tool helps us convert a sql query into a json. If it can help us convert a json into a sql query?

**Comment by klahnakoski** [comment]
There is a formatting function that does this.  I will update the docs if this is the case.

**Comment by klahnakoski** [comment]
the docs have been added here

https://github.com/mozilla/moz-sql-parser/pull/111/files#diff-04c6e90faac2675aa89e2176d2eec7d8R51

this PR will be merged shortly
