### ISSUE TITLE
No module named 'mo_future'

### ISSUE THREAD

**Issue by evan-burke** [mozilla/moz-sql-parser#11]
Getting this error in Jupyter, with Anaconda python 3.6.3.

Installed in Anaconda via pip- 
`Successfully installed moz-sql-parser-1.3.18033`

```
from moz_sql_parser import parse

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-18-9c8bbc990e39> in <module>()
----> 1 from moz_sql_parser import parse

~\Anaconda3\lib\site-packages\moz_sql_parser\__init__.py in <module>()
     14 import json
     15 
---> 16 from mo_future import text_type, number_types, binary_type
     17 from pyparsing import ParseException
     18 

ModuleNotFoundError: No module named 'mo_future'
```

Also tried in centos7 under py 3.6.3, same error. 
```Installing collected packages: pyparsing, moz-sql-parser
Successfully installed moz-sql-parser-1.3.18033 pyparsing-2.2.0

> python3 test.py

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    from moz_sql_parser import parse
  File "/home/vagrant/python/sqlparser/ve/lib/python3.6/site-packages/moz_sql_parser/__init__.py", line 16, in <module>
    from mo_future import text_type, number_types, binary_type
ModuleNotFoundError: No module named 'mo_future'
```

**Comment by evan-burke** [comment]
Looks like the mo_future module in requirements.txt wasn't installed automatically by pip.  Manually installing mo_future fixed that, so the workaround is easy, though the expectation is that pip installs will take care of all dependencies.

**Comment by klahnakoski** [comment]
The problem appears to be in `setup.py`.  I will fix it and deploy to pypi, but not until later this week. I hope to add an install test so this does not happen in the future.

**Comment by klahnakoski** [comment]
I think this is fixed now with https://github.com/mozilla/moz-sql-parser/commit/cb41d1292b7a3b70de91018b928fcb1fdb478634 . Deployed as https://pypi.org/project/moz-sql-parser/2.15.18155/
