### ISSUE TITLE
What would be the right approach to customise the supported grammar here?

### ISSUE THREAD

**Issue by gcobr** [mozilla/moz-sql-parser#130]
I need to fork this and customise the supported grammars a little.
I need to support unquoted identifiers like `{SOMETHING:SomethingElse}` for column names or aliases.

The way `sql_parser.py` is written defines the grammar as soon as the file is imported, leaving no room to change it. I reckon I'd need to change the assignment on line 244 from
~~~python
ident = Combine(~RESERVED + (delimitedList(Literal("*") | identString | mysqlidentString | Word(IDENT_CHAR), delim=".", combine=True))).setName("identifier")
~~~
to something like
~~~python
ident = Combine(~RESERVED + (delimitedList(Literal("*") | identString | myCustomIdentifier  | Word(IDENT_CHAR), delim=".", combine=True))).setName("identifier")
~~~

Would that make sense?

Is there any other recommended approach?

**Comment by klahnakoski** [comment]
Yes, that makes sense.  Fork this repo, and make your changes to the file.  The `sql_parser.py` is building a grammar tree; you intend to make a (slightly) different grammar tree.  It is best to write your own (or fork-and-change); there is no nice way to patch an existing grammar.  If done right, you may find your change hardly conflicts with changes here: You can occasionally merge updates from this repo into your fork.
