### ISSUE TITLE
Customizing the SQL parser definition

### ISSUE THREAD

**Issue by podhmo** [mozilla/moz-sql-parser#135]
I will parsing aiosql's query definition using moz-sql-parser, like below.

```sql
-- name: get-user-by-username^
select userid,
       username
  from users
 where username = :username;
```

More detail is here. https://nackjicholson.github.io/aiosql/defining_queries.html#select-one-row-with

In the aiosql query definition, the identifier contains the character ':', but the current moz-sql-parser parser definition will reject this kind of input .
(Of course, this could be viewed as an invalid SQL, not a complete SQL, so it's not a mistake)

As a workaround, I fork and change the code as follows and it parsed correctly. However, I don't want to maintain the forked code.

```diff
diff --git a/moz_sql_parser/sql_parser.py b/moz_sql_parser/sql_parser.py
index 469a214..ec07bb6 100644
--- a/moz_sql_parser/sql_parser.py
+++ b/moz_sql_parser/sql_parser.py
@@ -28,7 +28,7 @@ ParserElement.enablePackrat()
 # PYPARSING USES A LOT OF STACK SPACE
 sys.setrecursionlimit(3000)
 
-IDENT_CHAR = alphanums + "@_$"
+IDENT_CHAR = alphanums + "@_$:"
 
 KNOWN_OPS = [
     # https://www.sqlite.org/lang_expr.html
```
And not always including ':' char as the member of identifier.
So I would be happy if a way exists to customize the SQL parser definition.

**Comment by klahnakoski** [comment]
The best solution; is to maintain your fork:  Git will make this reasonably easy. Whenever you are inclined, merge this project's `master` branch with your branch. The merge should work without incident; especially since we are not expecting to change the `IDENT_CHAR` often.

**Comment by podhmo** [comment]
OK
