### ISSUE TITLE
Is there any plans to use latest version of pyparsing?

### ISSUE THREAD

**Issue by geoffkoh** [mozilla/moz-sql-parser#138]
Currently the requirements.txt pin this library to a fixed version of pyparsing.

pyparsing==2.3.1

Currently pyparsing is already at 2.4.7 (and 3.0.0 is coming around soon). Wondering if there is any issues updating the requirements of pyparsing to newer versions.

Thanks
Geoffrey

**Comment by klahnakoski** [comment]
There are plans.  There is one application that uses it and is still using py2: Conversion of that app is being done now.

**Comment by klahnakoski** [comment]
this project now uses a pyparsing derivative  https://github.com/klahnakoski/moz-sql-parser/commit/c6f937dfd7d754842c4ce23f0f68bfcb5f253147
