### ISSUE TITLE
not support like query

### ISSUE THREAD

**Issue by faryang-sh** [mozilla/moz-sql-parser#14]
when sql is 'like' query,it throw pyparsing.ParseException: Expecting one of .
i find the source code not contains 'like' function

**Comment by klahnakoski** [comment]
Thank you for filing a bug.  You are correct, the `like` expression is not supported. Are you willing to send a pull request to fix this?

**Comment by faryang-sh** [comment]
i send a pull request to fix this problem,you can check it.

**Comment by klahnakoski** [comment]
resolved with https://github.com/mozilla/moz-sql-parser/commit/00f4cd05cfd5f1c5e768f019f9c3d5387190480f
