### ISSUE TITLE
parsing issue for oracle window function

### ISSUE THREAD

**Issue by mosescha72** [mozilla/moz-sql-parser#140]
Is window function parsing  supported by moz-sql-parser ?

test ) 
-- window function over ( partition by    order by    ) 
   >  sum, min, max, rank, lead, lag is included in window function  

select rank(*) over (partition by a  order by b ) 
from tab 

Thank you for your support in advance

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/moz-sql-parser/commit/6e4361b76e599e3e948f6bba599d2eb22eb40df4#diff-61d5a1a018e97cc478eba974e6abfff036bf58e449578b7b680fab7f2e63976dR1056

**Comment by fredthedead** [comment]
https://github.com/klahnakoski/moz-sql-parser/commit/6e4361b76e599e3e948f6bba599d2eb22eb40df4#r44880533
