### ISSUE TITLE
Expecting StringEnd, found "xxx" (at char 388, (line:1, col:389)	

### ISSUE THREAD

**Issue by RemilYoucef** [mozilla/moz-sql-parser#154]
Hey, I'm having an issue, is that because the parser cannot handle very long strings ?

**Comment by klahnakoski** [comment]
It should be able to handle long strings.  It is either a problem in the SQL, or a bug in moz-sql-parser.  Please send me the SQL that's the problem.

**Comment by RemilYoucef** [comment]
I'm using your parser for hibernate queries, where there are keywords like, inner join fetch, i checked in the keywords file, and I didn't find it, so i replace my "inner join fetch" to "inner join" to test, and it works. 

Thank you
