### ISSUE TITLE
Parser not working

### ISSUE THREAD

**Issue by Turokhunter** [mozilla/moz-sql-parser#156]
I'm trying to parser the SDSS query dataset and this is one of their tutorial query examples.
http://skyserver.sdss.org/dr16/en/help/docs/realquery.aspx

SELECT TOP 10 u,g,r,i,z,ra,dec, flags_r
FROM Star
WHERE
  ra BETWEEN 180 and 181 AND dec BETWEEN -0.5 and 0.5
  AND ((flags_r & 0x10000000) != 0)
  AND ((flags_r & 0x8100000c00a4) = 0)
  AND (((flags_r & 0x400000000000) = 0) or (psfmagerr_r <= 0.2))
  AND (((flags_r & 0x100000000000) = 0) or (flags_r & 0x1000) = 0)

There few other queries that cannot be parsed.

SELECT TOP 10 fld.run,
           fld.avg_sky_muJy,
           fld.runarea AS area,
           ISNULL(fp.nfirstmatch, 0)
FROM
  (SELECT run,
          sum(primaryArea) AS runarea,
          3631e6*avg(power(cast(10. AS float), -0.4*sky_r)) AS avg_sky_muJy
   FROM Field
   GROUP BY run) AS fld
LEFT OUTER JOIN
  (SELECT p.run,
          count(*) AS nfirstmatch
   FROM FIRST AS fm
   INNER JOIN photoprimary AS p ON p.objid=fm.objid
   GROUP BY p.run) AS fp ON fld.run=fp.run
ORDER BY fld.run

The 3631e6 is not supported.

**Comment by klahnakoski** [comment]
This is an interesting flavour of SQL:   `3631e6avg(...)`  appears to be short form for `3631*10^6*AVG(...)`  I am not sure how easy it is to make `*` an optional operator.   I also see other not-handled cases, which are minor.  I will get back to you on this.

**Comment by klahnakoski** [comment]
This is an interesting parser, consider

```
SELECT -0.4sky_r
```

which can be interpreted as

```
SELECT -0.4 AS sky_r
```

or

```
SELECT -0.4 * sky_r
```

In order to interpret this as the latter case, there must be a special pattern `[number][no space][not number]` to ensure backwards compatibility

**Comment by Turokhunter** [comment]
I believe the SDSS is written using Microsoft SQL Server. 

I wonder if you can only use that short form when dealing with math formula.

**Comment by Turokhunter** [comment]
![image](https://user-images.githubusercontent.com/7236305/116826794-a63edf80-ab4a-11eb-857b-4002ff92e8f9.png)
I just double-checked the query and there is a * between 3631e6 and avg. It seems copying and pasting into the here removes multiply operator after submitting. I'm sorry about that.

**Comment by klahnakoski** [comment]
> . It seems copying and pasting into the here removes multiply operator 

😄 well, too late.  I now have a solution.  I have some extra work to do before packaging it.

**Comment by klahnakoski** [comment]
@Turokhunter   the update has been released.  Thank you for reporting this SQL query, it showed a few problems

* `3631e6` - can now parse integers with "E" notation
* `FLOAT` - was missing as a datatype
* `3x` - numeric-prefix-is-multiplication (as a mathematician, I enjoy)

**Comment by Turokhunter** [comment]
Sweet, thank you. I will check how many queries the parser passes now.
