### ISSUE TITLE
cannot parse the LIKE syntax

### ISSUE THREAD

**Issue by Bhanoday55** [mozilla/moz-sql-parser#19]
Hi

I'm writing a sql query which contains LIKE syntax and it's giving an error.

$ json.dumps(parse("select empid from emp where ename like 's%' "))

**Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    json.dumps(parse("select empid from emp where ename like 's%' "))
  File "C:\Python27\lib\site-packages\moz_sql_parser\__init__.py", line 33, in parse
    raise ParseException(sql, e.loc, "Expecting one of (" + (", ".join(expecting)) + ")")
ParseException: Expecting one of (and, gt, is, in, eq, sub, union, add, group by, lt, mult, between, order by, neq, func_param, concat, gte, having, limit, lte, collate nocase, div, or) (at char 34), (line:1, col:35)**

Please resolve.

**Comment by klahnakoski** [comment]
Sorry for the late reply, I did not notice your issue in my bug mail.

I will check into this shortly

**Comment by klahnakoski** [comment]
The expression you gave me parses

https://github.com/mozilla/moz-sql-parser/commit/048108010d0ce774c606b29db6cfb77591d9f9e3

Since I am in the process of updating this library, I will release a new version anyway.

**Comment by klahnakoski** [comment]
Looks good on py3.6

```
C:\Users\kyle\code>c:\python36\python.exe -m pip install --upgrade moz-sql-parser
Collecting moz-sql-parser
  Downloading https://files.pythonhosted.org/packages/ef/e5/2fa06731419ad6ac9742f893f30ad4f8e40c82f7069336cb7effd058130d/moz-sql-parser-2.18.18240.tar.gz
Requirement already up-to-date: mo-future>=2.18.18240 in c:\python36\lib\site-packages (from moz-sql-parser)
Requirement already up-to-date: pyparsing in c:\python36\lib\site-packages (from moz-sql-parser)
Building wheels for collected packages: moz-sql-parser
  Running setup.py bdist_wheel for moz-sql-parser ... done
  Stored in directory: C:\Users\kyle\AppData\Local\pip\Cache\wheels\7b\2b\8d\7905ce6dcb205baa7258e425d377ce9bd2c851be9f7f4a10cc
Successfully built moz-sql-parser
Installing collected packages: moz-sql-parser
Successfully installed moz-sql-parser-2.18.18240
You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\kyle\code>c:\python36\python.exe
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>>
>>> import json
>>> from moz_sql_parser import parse
>>> json.dumps(parse("select empid from emp where ename like 's%' "))
'{"select": {"value": "empid"}, "from": "emp", "where": {"like": ["ename", {"literal": "s%"}]}}'
>>>
```

**Comment by Bhanoday55** [comment]
Actually when I'm running with Python 3.7, there is ModuleNotFoundError.
Please help me out.

**Comment by klahnakoski** [comment]
Oh! 3.7!  The new versions of Python come out fast and furious!  Give me a day to check it out.

**Comment by klahnakoski** [comment]
Maybe the problem was with the documentation?  

https://github.com/mozilla/moz-sql-parser/tree/dev/tests#running-tests

I added the line 
 
    pip install -r requirements.txt

I installed Python3.7, and I could run the tests:

```
Microsoft Windows [Version 10.0.17134.228]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\kyle>cd code

C:\Users\kyle\code>cd moz-sql-parser

C:\Users\kyle\code\moz-sql-parser>c:\Python37\python.exe -m pip install -r tests\requirements.txt
Successfully installed mo-collections-2.18.18240 mo-dots-2.18.18240 mo-future-2.18.18240 mo-kwargs-2.18.18240 mo-logs-2.18.18240 mo-math-2.18.18240 mo-testing-2.18.18240 mo-times-2.18.18240

C:\Users\kyle\code\moz-sql-parser>c:\Python37\python.exe -m pip install -r requirements.txt
Successfully installed pyparsing-2.2.0

C:\Users\kyle\code\moz-sql-parser>set PYTHONPATH=.

C:\Users\kyle\code\moz-sql-parser>python.exe -m unittest discover tests
...........................................................................................................................................................................s............
----------------------------------------------------------------------
Ran 184 tests in 13.386s

OK (skipped=1)
```

Please include more details about the error, if it still exists.

**Comment by klahnakoski** [comment]
Please re-open if this is still an issue
