### ISSUE TITLE
Support ORDER BY ASC

### ISSUE THREAD

**Issue by msohcw** [mozilla/moz-sql-parser#2]
I note that this library is intended for a small basic subset of SQL. I'm interested in adding the two pieces of functionality (support `Identifier LIKE Pattern` and explicit `ASC`) as it is necessary for my use case. Would such a contribution be welcome?

**Comment by klahnakoski** [comment]
Yes please!

**Comment by klahnakoski** [comment]
How is it going? If you have questions, you can talk to me live most days on #ateam on irc:  ekyle@irc.mozilla.org

**Comment by klahnakoski** [comment]
Any work on the `like` expression will be done on https://github.com/mozilla/moz-sql-parser/issues/14

**Comment by klahnakoski** [comment]
fixed with https://github.com/mozilla/moz-sql-parser/commit/5e1c5df97d8f87d818deb1e97b82cb5ced442d25
