### ISSUE TITLE
Formatter does not pass new test suite

### ISSUE THREAD

**Issue by klahnakoski** [mozilla/moz-sql-parser#27]
The new `TestFormatAndParse` suite has 49 failed tests, and a few skipped tests that may also fail.
 
For example, `test_format_and_parse.TestFormatAndParse.test169()` fails because `moz_sql_parser.formatting.orderby()` is expecting a `dict`, but should handle `list`s of `dict`s too.

We can skip the broken tests for now, but this issue will stay open until this suite passes.

**Comment by Ajitesh13** [comment]
Can i take this bug ?

**Comment by klahnakoski** [comment]
fixed with https://github.com/mozilla/moz-sql-parser/pull/147
