### ISSUE TITLE
Lists of literals are collapsed into one literal block, unless there is one non-literal in the list.

### ISSUE THREAD

**Issue by EraYaN** [mozilla/moz-sql-parser#38]
Literals lists do not seem to be consequently collapsed.

`a IN ('abc','def')` parses to `{'in': ['a', {'literal': ['abc', 'def']}]}` while one would expect `{'in': ['a', [{'literal': 'abc'}, {'literal': 'def'}]]}`
while
`a IN ('abc',3,'def')` parses to `{'in': ['a', [{'literal': 'abc'}, 3, {'literal': 'def'}]]}`

appending more string literals to the end will keep them separated. This seems like a non-intentional feature. The same happens with function arguments. When using the parser to create tree, this requires an extra preprocessing step, to de-collapse and expand the literal objects.

**Comment by klahnakoski** [comment]
Before this is fixed, ActiveData (that uses this parser) will require some fixes:  https://github.com/mozilla/ActiveData/issues/150

**Comment by klahnakoski** [comment]
The current behaviour can not be changed:  The depth of the literal may not be bounded, it may be arrays-of-arrays, which raises the question what depth the `literal` is designated:  The answer is the highest level (for minimum `literal` calls).  

You are correct about `{'in': ['a', [{'literal': 'abc'}, 3, {'literal': 'def'}]]}` being wrong.  This has been fixed some time ago.

https://github.com/mozilla/moz-sql-parser/pull/116/files
