### ISSUE TITLE
More helpful error messages 

### ISSUE THREAD

**Issue by klahnakoski** [mozilla/moz-sql-parser#4]
From https://github.com/klahnakoski/mo-logs/issues/2 :

```
Traceback (most recent call last):
  File "/Users/andersh/Projects/moz-sql-parser/tests/test_simple.py", line 113, in test_bad_select1
    self.assertRaises('Expected select', lambda: parse("se1ect A, B, C from dual"))
  File "/Users/andersh/Projects/moz-sql-parser/venv/lib/python2.7/site-packages/mo_testing/fuzzytestcase.py", line 69, in assertRaises
    cause=f
  File "/Users/andersh/Projects/moz-sql-parser/venv/lib/python2.7/site-packages/mo_logs/__init__.py", line 398, in error
    raise e
Except: ERROR: expecting an exception returning "Expected select" got something else instead
```

That's a deeply unhelpful message. You should print what that "something else" is.

**Comment by boxed** [comment]
You should probably move the entire test suite over to pytest and vastly simplify all that code.

**Comment by klahnakoski** [comment]
On the subject of the error message: It is a result of a test not passing, and I can not think of anything more the error could say; it expects an exception, and it did not get one.

On the subject of pytest: pytest will not reduce the code complexity. The `FuzzyTestCase` does a fuzzy data- structure comparison between a `test` and an `expected`.  I must review the tests in py2.7 to see if any "fuzzy" features are used.  If not, then this dependency can be removed.

**Comment by boxed** [comment]
> , and I can not think of anything more the error could say; it expects an exception, and it did not get one.

No that's not the problem at all. Read more carefully. It expects an assertionerror that contains the string "Expected select". I was working on trying to expand moz-sql-parser to cover more SQL syntax.

I'm still pretty sure this error message is actually in the logging module where I first created the issue. The exception should have been "expected foo, found bar". It's just a string comparison!

**Comment by klahnakoski** [comment]
Yes, the test on line 113 (`test_bad_select1`) is verifying that an exception is thrown when the first word in the SQL is not "select".  Specifically, the third letter is the number one (`1`), not the letter `L` as would be expected.  

`test_bad_select1` is expecting "Expecting select" somewhere in the parsing exception.  I believe "Expecting select" is a good message if the first word is not "select", and I believe `test_bad_select1` can not get much clearer.  Maybe you have a suggestion for a better error message? 

Since I can not get `pyparsing` to work with Python3, maybe you can use python2 in the meantime?

https://github.com/mozilla/moz-sql-parser/issues/3

**Comment by boxed** [comment]
I was trying to add support for create table statements to this lib. Try it yourself and see what happens with the tests. They fail with a bad error message that is NOT from pyparsing because that lib gives quite sane error messages. 

I should say that I’ve since given up in this project because I found this lib and its dependencies to be in a sorry state quite frankly. There were a lot of paper cuts in a surprisingly short time.

**Comment by klahnakoski** [comment]
Please push your changes, and send me a link. I would like to see how far you got, and incorporate what you have done so it is less painful for the next person.

thank you for your time on this.

**Comment by boxed** [comment]
I’ve deleted them. I came to the conclusion that working with Python-sqlparse despite its weirdness was a better idea. Sorry about that.
