### ISSUE TITLE
Recursion Depth

### ISSUE THREAD

**Issue by todpole3** [mozilla/moz-sql-parser#41]
I encountered a tricky issue when parsing SQL queries with nested parenthesis in logic expressions.

For example, when I use the default code to parse the query
```
SELECT * FROM A WHERE false and ((not ((true) or (false))))
```
I encounter the error `RecursionError: maximum recursion depth exceeded while calling a Python object`.

The issue can be resolved by lifting the system recursion limit to 10000, with which the parser outputs the correct parse
```{
    "select": "*",
    "from": "A",
    "where": {
        "and": [
            "false",
            {
                "not": {
                    "or": [
                        "true",
                        "false"
                    ]
                }
            }
        ]
    }
}
```

I'm not completely familiar with how pyparsing works. Could someone explain in this case why the recursion depth has exceeded 1500 or could this be possibly caused by a bug?

**Comment by klahnakoski** [comment]
Yes, I know of this problem.  pyparsing's `infix_notation()` generates code that uses excessive stack and a parsing algorithm that is O(2^N) (N is number of operators).  We can increase the stack depth, but that would also increase the CPU effort exponentially; and consume all CPU of whatever machines runs this code.  We can not increase the stack limit, it is too dangerous.

I started a PR with the hope of a low-level fix https://github.com/mozilla/moz-sql-parser/pull/37  My plan was to understand pyparsing, attempt a fix, and then simplify my fix enough to make a PR to the pyparsing project. I am only at the point of understanding the code enough to fix `infix_notation()`.  *I have not started a fix yet*.

There are two solutions: The first, what I was attempting: To fix infix_notation().  The other is to parse expressions as an alternating list of operand/operators, and then do some post processing to build the parse tree from that list.  The solutions are very similar, with the former being slightly general form for the latter.

**Comment by todpole3** [comment]
This makes sense to me. And this is probably important since there are a long tail of operators to be introduced to the library, such as the different types of joins.

**Comment by polarisary** [comment]
Does this bug fixed?

**Comment by klahnakoski** [comment]
@polarisary This bug is as fixed as it can be.  The real solution is in pyparsing, but that did not happen last year, so I do not expect it to happen this year.  The best I can do is add documentation on how to increase the recursion limit before parsing

https://github.com/mozilla/moz-sql-parser/pull/115/files#diff-04c6e90faac2675aa89e2176d2eec7d8R51
