### ISSUE TITLE
Re-add setup.py to repo so that installs can be done from git URL

### ISSUE THREAD

**Issue by DolanMaize** [mozilla/moz-sql-parser#46]
It looks like you removed setup.py from the repo and instead have some external tool generate it when doing releases.  Unfortunately, by not having a setup.py file in the repo, a pip install from a git URL fails with an error about setup.py being missing.

I ran into this issue when trying to install my fork of the project via: `pip install git+https://github.com/pydolan/moz-sql-parser.git@new-join-types`.  My workaround is to just copy the library into my project until my recent change gets merged, but having the setup.py would help me avoid this minor work (and ease pressure on your end to push releases out often).

Thoughts?

**Comment by klahnakoski** [comment]
I never considered that use case.  I added back the setup.py (which is auto generated): https://github.com/mozilla/moz-sql-parser/commit/67be389ea8bce13aa7cdcdf5e8a7494c1580e5d5  

It seems to work for me.  Please confirm works for you too.

**Comment by DolanMaize** [comment]
Perfect, thanks!  Thanks for also pushing out a new version to pypi so quickly.

I verified that `pip install git+https://github.com/mozilla/moz-sql-parser.git@dev` installed the package as expected
