### ISSUE TITLE
Trailing semicolon in provided SQL causes parsing error

### ISSUE THREAD

**Issue by pydolan** [mozilla/moz-sql-parser#49]
While it's easy enough to parse out a trailing semicolon, it might be good to ignore it if it's the last character in the provided SQL statement.  Thoughts?

**Comment by klahnakoski** [comment]
that sounds like a nice feature.  I have also had SQL with trailing semicolons

**Comment by nishikeshKardak** [comment]
Is this issue still open? If yes, then can I work on it??

**Comment by klahnakoski** [comment]
@nishikeshKardak  This has been solved.  Sorry I did not close this.
