### ISSUE TITLE
Usage of "NOT" before operators fails (e.g., "NOT LIKE", "NOT IN", etc)

### ISSUE THREAD

**Issue by pydolan** [mozilla/moz-sql-parser#52]
A query such as `SELECT col1 FROM table1 WHERE col0 NOT IN (1, 2)` will fail with a `ParseException("expecting one of ...")`, however, `SELECT col1 FROM table1 WHERE NOT col0 IN (1, 2)` will parse okay.  

A solution to #48 might address this, but as an alternative, I'm thinking we can simply create a few new keywords to address this ("not in", "not between", "not like", etc.).  Thoughts?

**Comment by klahnakoski** [comment]
I reopened two PRs that may deal with this.

https://github.com/mozilla/moz-sql-parser/pull/42
https://github.com/mozilla/moz-sql-parser/pull/43

Please look them over, if they are good for you too, then I will merge them.

**Comment by pydolan** [comment]
They look good to me, basically matching the PR I was just about to submit (except I also added `NOT BETWEEN` and `NOT IS`). I can revise my change to get these last two once you merge #42 and #43 in.

I know we don't want to increase the recursion limit, but for my changes, I two of the tests failing until I creased the recursion limit from 1500 to 2000.  

I read through #17 and #41, and it sounds like the fix for #41 will address this, but in the meantime, do you want me to increase this to 2000 so that the current set of tests pass?
