### ISSUE TITLE
Add CREATE TABLE syntax

### ISSUE THREAD

**Issue by klahnakoski** [mozilla/moz-sql-parser#6]
It would be nice to support CREATE TABLE, and maybe some other metadata operations too.

**Comment by klahnakoski** [comment]
I had a good question regarding what the JSON output should be.  Here is my suggestion:

```javascript
{ "create table": {
    "name": "student",
    "columns": [
        "name": "varchar",
        "age": "int",
        "roll_no": "int"
    ]
}}
```

**Comment by nishikeshKardak** [comment]
Can we add column size in JSON output as follows?
{
    "name": "name",
    "type": "varchar",
    "size": "25"
}

**Comment by ykawakamy** [comment]
I'm sorry. I didn't mean to notify you here yet.

I'd like to start working on this issue.

I'm working on fixing the points raised in pull #86.
In addition, I would like to implement the CREATE TABLE SELECT syntax at the same time.

How about it?

---
sry, I can't speak English well...

**Comment by klahnakoski** [comment]
@ykawakamy   Active development is happening on a fork: https://github.com/klahnakoski/moz-sql-parser

I will continue to follow the issue here, if that is easier for you.  

I am a little slow at responding, but feel free to ask questions if you want some help.

**Comment by klahnakoski** [comment]
@nishikeshKardak has suggested something like 

```
{
    "name": "name",
    "type": "varchar",
    "size": "25"
}
```

which may be fine.   We should look at other places where type information is provided.  For example, `CAST(2008 AS CHAR(4))` gets translated to `{"cast": [2008, {"char": 4}]}}})`.  Maybe types should look like functions

```
{
    "name": "name",
    "type": {"varchar":25}
}
```

since `DECIMAL()` takes two parameters, this functional style my be more flexible.

We should also consider BigQuery's "Standard"  SQL;  The column types can be whole data structures, including arrays.  If we choose a style that works recursively, then we can deal with BigQuery table definitions in the future.


https://cloud.google.com/bigquery/docs/nested-repeated

**Comment by klahnakoski** [comment]
...  for clarity, I am not against this style:

```
{
    "name": "name",
    "type": "varchar",
    "size": "25"
}
```

it has an advantage of making the `size` explicit, and it is easier to digest with code.

**Comment by ykawakamy** [comment]
Thank you, @klahnakoski .

I'll pull your repository when I'm done fixing the pointers.

> since DECIMAL() takes two parameters, this functional style my be more flexible.

e.g.
```
{
    "name": "money",
    "type": {"decimal":[25, 20]}
}
```

> We should also consider BigQuery's "Standard" SQL; The column types can be whole data structures, including arrays. If we choose a style that works recursively, then we can deal with BigQuery table definitions in the future.

I was looking at the BigQuery's syntax. 
https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_table_statement
I will work on it if possible.

**Comment by ykawakamy** [comment]
The implementation of the create table syntax is mostly finished.

I'm still working on some implementations, but I'd like to have them reviewed.
Can I submit a PR to your fork? Or Mozilla?

TODO:
- [x] Implementation of "column constraint definition".  
  - [x] Support for nested type(BigQuery's "STRUCT" and "ARRAY") in column_type 
- [x] Implementation of "table constraint definition".  ( e.g. "FOREIGN KEY"  )
- [x] Merge column_type and known_types
  - [x] Support for user-defined types.( allow unknown type )

**Comment by ykawakamy** [comment]
When I was writing tests, I found that null was not interpreted.

I guess , there is a issue with[ utils.py#scrub()](https://github.com/ykawakamy/moz-sql-parser/blob/5079b15c3d0f0bcda644a5cc894a75429dade43e/moz_sql_parser/utils.py#L29) or my implementation.

added [tests](https://github.com/ykawakamy/moz-sql-parser/blob/5079b15c3d0f0bcda644a5cc894a75429dade43e/tests/test_commands.py#L104) in my fork.

**Comment by klahnakoski** [comment]
@ykawakamy  please submit to my fork.  thank you

**Comment by klahnakoski** [comment]
> I guess , there is a issue with utils.py#scrub() or my implementation.

Yes, I hope to remove the need for `scrub()` the output is not defined clearly enough, and it is source of bugs for that reason.  You pointed to one problem; another problem is a list-with-single-value (`[anything]`) gets mapped to single-value (`anything`), which Removes a number of `Group()` elements.
