### ISSUE TITLE
SQL Parse error

### ISSUE THREAD

**Issue by pedrohcdo** [mozilla/moz-sql-parser#63]
"SELECT oc.dh_registro, oc.id_cliente, cli.nome_reduzido, cli.id_cliente, oc.id_proc_padrao, oc.texto_ocorrencia, count(1) as 'quantidade', opc.contagem_min, opc.contagem_max FROM ocorrencias oc LEFT JOIN ocorrencia_padrao_cliente opc ON oc.id_proc_padrao = opc.id_proc_padrao INNER JOIN cliente cli ON oc.id_cliente = cli.id_cliente WHERE oc.dh_registro BETWEEN '2019-01-07 00:00:00' AND NOW() AND cli.id_cliente='5781' AND oc.oco_cancelada=0 GROUP BY oc.id_proc_padrao ORDER BY oc.id_proc_padrao"

This SQL is not parsing, any suggestions?

**Comment by klahnakoski** [comment]
Sorry for the late reply, I did not see this issue:

The problem is here: `count(1) as 'quantidade'`  identifiers must be in double quotes, not single quotes
