### ISSUE TITLE
I am totally new to Python and linux territory. So when I do PIP I get an error. Can anybody tell me why is that? Also should i run this command in the parent directory where parser is or within the parser directory? Thanks in advance!

### ISSUE THREAD

**Issue by js5395** [mozilla/moz-sql-parser#64]
Could not find a version that satisfies the requirement moz-sql-parser-dev (from versions: )
No matching distribution found for moz-sql-parser-dev

**Comment by klahnakoski** [comment]
Sorry I missed this issue. I hope you are fine now,
