### ISSUE TITLE
moz-sql-parse recursion crashes Python

### ISSUE THREAD

**Issue by CharellKing** [mozilla/moz-sql-parser#68]
select deflate(ceo.name, 'ceo_name', mobile_price.type, sum(int(mobile_price.price)), '0:普通,1:旗舰', 0) from mobile, company, ceo, mobile_price where mobile.id = mobile_price.mobile_id and mobile.company_id = company.id and company.id = ceo.company_id group by ceo.name, mobile_price.type

**Comment by CharellKing** [comment]
File "/Users/andy/.pyenv/versions/3.5.6/lib/python3.5/site-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/Users/andy/.pyenv/versions/3.5.6/lib/python3.5/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/andy/.pyenv/versions/3.5.6/lib/python3.5/site-packages/pyparsing.py", line 3530, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/Users/andy/.pyenv/versions/3.5.6/lib/python3.5/site-packages/pyparsing.py", line 1529, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/Users/andy/.pyenv/versions/3.5.6/lib/python3.5/site-packages/pyparsing.py", line 1373, in _parseNoCache
    preloc = self.preParse( instring, loc )
  File "/Users/andy/.pyenv/versions/3.5.6/lib/python3.5/site-packages/pyparsing.py", line 1330, in preParse
    loc = self._skipIgnorables( instring, loc )
  File "/Users/andy/.pyenv/versions/3.5.6/lib/python3.5/site-packages/pyparsing.py", line 1322, in _skipIgnorables
    loc,dummy = e._parse( instring, loc )
  File "/Users/andy/.pyenv/versions/3.5.6/lib/python3.5/site-packages/pyparsing.py", line 1525, in _parseCache
    value = cache.get(lookup)
  File "/Users/andy/.pyenv/versions/3.5.6/lib/python3.5/site-packages/pyparsing.py", line 1463, in get
    return cache.get(key, not_in_cache)
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by CharellKing** [comment]
select deflate(ceo.name, 'ceo_name', mobile_price.type, sum(mobile_price.price), '0:普通,1:旗舰', 0) from mobile, company, ceo, mobile_price where mobile.id = mobile_price.mobile_id and mobile.company_id = company.id and company.id = ceo.company_id group by ceo.name, mobile_price.type


this sql is ok, but only nest "int" function in "sum" function. the pyparsing recursion error

**Comment by klahnakoski** [comment]
Thank you for this report.  This problem is known https://github.com/mozilla/moz-sql-parser/issues/41  and [I hope we have a GSOC student to fix this in the summer](https://github.com/mozilla/moz-sql-parser/blob/dev/docs/Student%20Project%202019.md)

**Comment by klahnakoski** [comment]
In the meantime, you can increase the recursion limit:

    sys.setrecursionlimit(2000)

seen at 

https://github.com/mozilla/moz-sql-parser/blob/dev/moz_sql_parser/sql_parser.py#L22

**Comment by klahnakoski** [comment]
Hmm, this query is worse than I thought; it seems the crash Python (usually an out-of-memory event)

I made a test to capture this problem 

https://github.com/mozilla/moz-sql-parser/commit/cc5f713f1fe8c074da2973cf9b8a3ab0f2906dc4#diff-78104e5fa4dd93c4f81a6fe735e2098fR495

**Comment by klahnakoski** [comment]
@CharellKing  this test is passing with the higher recursion limit set.

**Comment by hhyo** [comment]
same problem
```
SELECT COUNT(*) AS CNT FROM test.tb WHERE (id IN (unhex('1'),unhex('2'))) AND  status=1;
```

**Comment by nishikeshKardak** [comment]
> same problem
> 
> ```
> SELECT COUNT(*) AS CNT FROM test.tb WHERE (id IN (unhex('1'),unhex('2'))) AND  status=1;
> ```

It also crashes with sys.setrecursionlimit(2000)

**Comment by RyanMarcus** [comment]
Here's another example [from the join order benchmark](https://github.com/gregrahn/join-order-benchmark) that requires setting the recursion limit to 2000.

https://repl.it/@RyanMarcus/mozsqlparse-recursion

**Comment by klahnakoski** [comment]
@RyanMarcus thank you for both a link to the benchmark, and another breaking example.  I will include the example here, just in case it falls down the memory hole.

```python
sql = """
SELECT * FROM aka_name AS an, cast_info AS ci, info_type AS it, link_type AS lt, movie_link AS ml, name AS n, person_info AS pi, title AS t WHERE
an.name  is not NULL
and (an.name LIKE '%a%' or an.name LIKE 'A%')
AND it.info ='mini biography'
AND lt.link  in ('references', 'referenced in', 'features', 'featured in')
AND n.name_pcode_cf BETWEEN 'A' AND 'F'
AND (n.gender = 'm' OR (n.gender = 'f' AND n.name LIKE 'A%'))
AND pi.note  is not NULL
AND t.production_year BETWEEN 1980 AND 2010
AND n.id = an.person_id AND n.id = pi.person_id AND ci.person_id = n.id AND t.id = ci.movie_id AND ml.linked_movie_id = t.id AND lt.id = ml.link_type_id AND it.id = pi.info_type_id AND pi.person_id = an.person_id AND pi.person_id = ci.person_id AND an.person_id = ci.person_id AND ci.movie_id = ml.linked_movie_id
"""
from moz_sql_parser import parse
# import sys
# sys.setrecursionlimit(2000)
parse(sql)
```

**Comment by klahnakoski** [comment]
fixed with https://github.com/mozilla/moz-sql-parser/commit/e42d17e8cdb810ff4d1f80f7ede09e0c603004be

added test https://github.com/mozilla/moz-sql-parser/commit/596b58b76dc66178f600f7da2e2ffd2217287f59

**Comment by klahnakoski** [comment]
added another test: https://github.com/mozilla/moz-sql-parser/commit/8ba65202204a08ac982c6ca30cb2a272e4807683

**Comment by klahnakoski** [comment]
Issue 41 is still a problem, but the specific sql in this issue have been resolved

**Comment by rcoup** [comment]
I'm seeing this running the test suite under Py3.7.4 on macOS (via Homebrew) as at 429eee0615507970722a557186a324fe77390daf:

1. `test_issue68 (test_simple.TestSimple)`
2. `test_issue68b (test_simple.TestSimple)`
3. `test_098 (test_resources.TestResources)`

all fail with `RecursionError: maximum recursion depth exceeded while calling a Python object`

(3) is skipped in CI when `TRAVIS_BRANCH=master` — the other test skipped in CI is `test_096 (test_resources.TestResources)`, but that passes locally for me.
