### ISSUE TITLE
Add CREATE VIEW syntax

### ISSUE THREAD

**Issue by nishikeshKardak** [mozilla/moz-sql-parser#71]
It would be nice to support CREATE VIEW.

**Comment by klahnakoski** [comment]
Even basic CREATE VIEW support would go a long way.

No need to implement all the options at first:

https://dev.mysql.com/doc/refman/8.0/en/create-view.html
https://www.postgresql.org/docs/9.4/sql-createview.html
https://docs.oracle.com/cd/B28359_01/server.111/b28286/statements_8004.htm#SQLRF01504

**Comment by nishikeshKardak** [comment]
I am closing this issue for now. But when we will implement all the options, I will reopen it and try to make PL.
