### ISSUE TITLE
Synthesize SQL from parsed results?

### ISSUE THREAD

**Issue by jbkoh** [mozilla/moz-sql-parser#9]
Thanks for sharing a useful project.

Is it possible to synthesize SQL string from the parsed results? I am trying to use this to modify queries, but I can't find how to synthesize SQL from the parsed dict. This project looks much simpler than [the other one](https://github.com/andialbrecht/sqlparse), and I'd go for this if it supports synthesizing. 

Thank you!

**Comment by klahnakoski** [comment]
Synthesizing SQL from the parse tree is an excellent idea!  Not only could people use the SQL output, but it can be used to verify parsing is consistent (verify JSON -> SQL -> JSON is the same, or at least tends to a fixed-point).

The bad news is there is no SQL synthesis,  I am keeping this issue open in case someone wants to write it.

Maybe you are interested in writing the first version of a `formatting.py` module?  It only needs to output a single format. There are not many different types of parsed tokens to format (sql statements, infix expressions, case statements, bracketed lists, function calls, and few others).

Whatever you decide, I wish you luck with your query modifications!

**Comment by jbkoh** [comment]
Thanks for the quick clarification. I can't guarantee to put an effort soon, but I will share here if I get a draft.
Thank you!

**Comment by betodealmeida** [comment]
@jbkoh @klahnakoski heads up, I have a PR addressing this.
