### ISSUE TITLE
bug in parsing ?

### ISSUE THREAD

**Issue by DelphianCalamity** [mozilla/moz-sql-parser#90]
It appears that the parser has trouble parsing correctly queries containing "IS NOT NULL".
It translates this to "exists" and then breaks or something?

e.g. this is the query:

`SELECT MIN(cn.name) AS from_company `
`FROM company_name AS cn,
     company_type AS ct,
     keyword AS k,
     movie_link AS ml,
     title AS t`
`WHERE cn.country_code !='[pl]'
  AND ct.kind IS NOT NULL
  AND t.production_year > 1950
  AND ml.movie_id = t.id
`

and this is its parsed version:

`
{ 'from': [ {'name': 'cn', 'value': 'company_name'},
            {'name': 'ct', 'value': 'company_type'},
            {'name': 'k', 'value': 'keyword'},
            {'name': 'ml', 'value': 'movie_link'},
            {'name': 't', 'value': 'title'}],
  'select': {'name': 'from_company', 'value': {'min': 'cn.name'}},
  'where': { 'and': [ {'neq': ['cn.country_code', {'literal': '[pl]'}]},
                      {'exists': 'ct.kind'}]}}
`

**Comment by klahnakoski** [comment]
Thank you!

https://github.com/mozilla/moz-sql-parser/commit/e42d17e8cdb810ff4d1f80f7ede09e0c603004be
