### ISSUE TITLE
Incorrect order of operations

### ISSUE THREAD

**Issue by ianmcook** [mozilla/moz-sql-parser#91]
Rules for order of operations specify that addition and subtraction have the same priority and should be applied from left to right. Similarly, multiplication and division have the same priority and should be applied from left to right. But the implementation in moz_sql_parser treats addition as higher priority than subtraction, and it treats multiplication as higher priority than division. For example, the output from moz_sql_parser is as follows:
```
>>> from moz_sql_parser import parse
>>> import json
>>> json.dumps(parse("select 5-4+2"))
'{"select": {"value": {"sub": [5, {"add": [4, 2]}]}}}'
>>> json.dumps(parse("select 5/4*2"))
'{"select": {"value": {"div": [5, {"mul": [4, 2]}]}}}'
```
To follow the rules for order of operations, the output should be as follows:

```
>>> json.dumps(parse("select 5-4+2"))
'{"select": {"value": {"add": [{"sub": [5, 4]}, 2]}}}'
>>> json.dumps(parse("select 5/4*2"))
'{"select": {"value": {"mul": [{"div": [5, 4]}, 2]}}}'
```

**Comment by klahnakoski** [comment]
This will make the parser logic more complicated.  It may be best introduced into pyparsing.

**Comment by klahnakoski** [comment]
https://github.com/pyparsing/pyparsing/issues/174

I am keeping this issue open because it is not that difficult to "just do it"

**Comment by klahnakoski** [comment]
The fix is here:

https://github.com/mozilla/moz-sql-parser/pull/111/commits/e383a573959c5f556bd2f6f3a5c69da6354565d8?w=1

**Comment by klahnakoski** [comment]
the PR will be merged shortly
