### ISSUE TITLE
Backticks in table name are being incorrectly escaped

### ISSUE THREAD

**Issue by enilsen16** [mozilla/moz-sql-parser#92]
Possibly related to #35

SELECT *  FROM \`movies\` when parsed and then formatted becomes SELECT * FROM "\`movies\`"

**Comment by enilsen16** [comment]
It looks like some of the tests may depend on incorrect behavior. 

```python
    def verify_formatting(self, expected_sql, expected_json):
        new_sql = ""
        new_json = ""
        try:
            new_sql = format(expected_json)
            new_json = parse(new_sql)
            self.assertEqual(new_json, expected_json)
        except Exception as e:
            raise VerificationException(expected_sql, expected_json, new_sql, new_json)
```

Changing the original function (above) to:
```python
    def verify_formatting(self, expected_sql, expected_json):
        new_sql = ""
        new_json = ""
        try:
            new_json = parse(expected_sql)
            new_sql = format(new_json)
            self.assertEqual(new_sql, expected_sql)
        except Exception as e:
            raise VerificationException(expected_sql, expected_json, new_sql, new_json)
```

really seems to break a lot of tests

**Comment by klahnakoski** [comment]
the `verify_formatting()` is only looking for stability: The SQL it generates can be parsed to the expected JSON.  This was done to quickly make many tests; assuming the parser is correct.  

In your case the parser is wrong.  I will fix that.

**Comment by klahnakoski** [comment]
fix is here

https://github.com/mozilla/moz-sql-parser/pull/111/commits/53b94ce97a94b6c1898070c0bd83cf02b73e8b6c

this will be merged shortly
