### ISSUE TITLE
Support for table-valued functions?

### ISSUE THREAD

**Issue by jn73** [mozilla/moz-sql-parser#95]
Our project needs to be able to parse "table-valued functions" as from statement, similar to what can be found in postgresql and sqlserver:

sqlserver:
`select * from some_table.some_function('parameter', 1, some_col)`

postgres:
`select * from some_func('parameter', 1, some_col)`

I've made a quick test and have this (kindof) working with the sqlserver syntax. I did run into a some problem when using a dot as separator for the function name (probably the matcher eagerly parsing the table name). So for now we use the following format:

`select * from some_table::myfunc(...)`

It would be great not having to maintain this fork. Can we submit a pull request (after fixing parsing issue "::") or is it outside of the scope of this project?

**Comment by klahnakoski** [comment]
@jn73   Does this look good (specifically the test)?  When using a function, you will have 

   {"from":{"value":{"function":[parameters]}}}   

This form will also assign a name, if you use `AS blah`...

   {"from":{"value":{"function":[parameters]}, "name":"blah"}}   

https://github.com/mozilla/moz-sql-parser/pull/113
